Repository apache/flink-connector-pulsar, pull requests merged in 2023-05, with the labels that each got.

#45 [hotfix] Workaround new violations message
  .github/workflows/daily.yml
  flink-connector-pulsar/archunit-violations/f4d91193-72ba-4ce4-ad83-98f780dce581
Labels: component=Connectors/Pulsar, component=BuildSystem

#46 [hotfix] Python connector download link should refer to the url defined in externalized repository
  docs/content.zh/docs/connectors/datastream/pulsar.md
  docs/content/docs/connectors/datastream/pulsar.md
  docs/data/pulsar.yml
Labels: component=Documentation

#47 [BP-3.0][hotfix] Python connector download link should refer to the url defined in externalized repository
  docs/content.zh/docs/connectors/datastream/pulsar.md
  docs/content/docs/connectors/datastream/pulsar.md
  docs/data/pulsar.yml
Labels: component=Documentation

#44 [FLINK-32003] Upgrade pulsar-client version to work with OAuth2
  flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchema.java
  flink-connector-pulsar/src/main/java/org/apache/flink/connector/pulsar/common/schema/PulsarSchemaUtils.java
  flink-connector-pulsar/src/test/java/org/apache/flink/connector/pulsar/testutils/runtime/container/PulsarContainerRuntime.java
  flink-sql-connector-pulsar/src/main/resources/META-INF/NOTICE
  pom.xml
Labels: component=Connectors/Pulsar

#50 [BP-4.0][FLINK-32024][docs] Short code related to externalized connector retrieve version from its own data yaml
  docs/content.zh/docs/connectors/datastream/pulsar.md
  docs/content/docs/connectors/datastream/pulsar.md
  docs/data/pulsar.yml
Labels: component=Documentation
