Repository apache/flink-connector-pulsar, pull requests merged in 2024-01, with the labels that each got.

#73 [FLINK-33964] Drop admin docs reference
  docs/content.zh/docs/connectors/datastream/pulsar.md
  docs/content/docs/connectors/datastream/pulsar.md
Labels: component=Documentation

#76 [BP][FLINK-33964][pulsar][docs] Drop admin docs reference
  docs/content.zh/docs/connectors/datastream/pulsar.md
  docs/content/docs/connectors/datastream/pulsar.md
Labels: component=Documentation

#77 [FLINK-33964][pulsar][docs] Remove dead link
  docs/content.zh/docs/connectors/datastream/pulsar.md
  docs/content/docs/connectors/datastream/pulsar.md
Labels: component=Documentation

#78 [FLINK-33970] Add necessary checks for connector document
  .dlc.json
  .github/workflows/ci.yml
Labels: component=BuildSystem

#79 [BP][FLINK-33964][pulsar][docs] Remove dead link
  docs/content.zh/docs/connectors/datastream/pulsar.md
  docs/content/docs/connectors/datastream/pulsar.md
Labels: component=Documentation, component=BuildSystem

#82 [hotfix] Update copyright year to 2024
  flink-sql-connector-pulsar/src/main/resources/META-INF/NOTICE
Labels: component=Connectors/Pulsar
